package com.example.movieapp.models

import com.example.movieapp.R


data class MovieStore(val myMovies: MutableList<Movie> = mutableListOf()){

    val defaultMovies = exampleMovies

    fun findMovieByUUID(uuid: String): Movie? {
        return defaultMovies.find { movie -> movie.id.toString() == uuid }
    }

    companion object{
        val exampleMovies: MutableList<Movie> = createStaticMovieList()

        private fun createStaticMovieList(): MutableList<Movie> {
            val list: MutableList<Movie> = mutableListOf()


            val movie1 = Movie("Whiplash", "Andrew Neiman is a first-year student at the prestigious Shaffer Conservatory in New York City. He has been playing drums from a young age and aspires to become a world-class drummer like Buddy Rich. Terence Fletcher, conductor and bandleader of Shaffer Conservatory Studio Band, invites him into the ensemble as alternate for core drummer Carl Tanner. However, Andrew quickly discovers that Fletcher is relentlessly strict, ruthless and abusive to his students. When the band rehearses the Hank Levy piece \"Whiplash\" and Andrew struggles to keep the tempo, Fletcher hurls a chair at him, slaps him multiple times and berates him in front of the ensemble.\n" +
                    "\n" + "In a jazz competition, after their first set, Andrew misplaces Tanner's sheet music. When called for their second set, Tanner cannot play without his sheets, but Andrew claims he can perform \"Whiplash\" from memory. After a successful performance, Fletcher promotes Andrew to core drummer for the Studio Band, but he also recruits Ryan Connolly, the core drummer from a lower-level ensemble within the conservatory. Andrew believes Connolly is a less talented drummer than he and is infuriated when Fletcher promotes Connolly to core. Determined to impress Fletcher, Andrew breaks up with his girlfriend, Nicole, to focus on his musical ambitions, and practices until his hands bleed. After a five-hour session with Tanner and Connolly for the core spot, in which Fletcher hurls objects and screams at them, Andrew finally earns back the core spot.\n" +
                    "\n" + "On the way to their next competition, the bus Andrew is riding breaks down. He rents a car but arrives late and realizes he left his drumsticks at the rental office. After convincing an impatient Fletcher to wait for him, Andrew races back and retrieves them, but his car is hit by a truck on the way back. He crawls from the wreckage and runs back to the theater, arriving just as the ensemble enters stage. Bloody and injured, Andrew struggles to play \"Caravan,\" in which Fletcher halts the performance and dismisses Andrew, who then attacks him on stage, resulting in his expulsion from Shaffer.\n" +
                    "\n" + "At his father's request, Andrew meets a lawyer representing the parents of Sean Casey, a former student of Fletcher, in an ethics complaint against Shaffer. Contrary to Fletcher's prior claim that Sean died in a car accident, the lawyer explains that Sean hanged himself out of depression and anxiety spurred on by Fletcher's abuse. Sean's parents want to see Fletcher forbidden from teaching again; Andrew agrees to testify as an anonymous witness, and Fletcher is fired.\n" +
                    "\n" + "Following his expulsion, Andrew has abandoned drumming and is working in a restaurant. He later discovers Fletcher performing as a pianist at a jazz club. Fletcher spots Andrew and invites him for a drink. Fletcher explains his dismissal from Shaffer and admits that his teaching methods were harsh, but he only wanted his students to push themselves to become their absolute best, referencing Charlie Parker's success story as an example. When Andrew asks if his methods would instead discourage students, Fletcher replies that the next Charlie Parker would never be discouraged. Fletcher invites Andrew to perform with his band at the JVC Jazz Festival, as they would be playing the songs Andrew was confident in from their time at Shaffer, and Andrew accepts. Andrew invites Nicole to the performance, but she declines as she is in a new relationship.\n" +
                    "\n" + "Andrew arrives at JVC and the band goes onstage. Just before they begin their first piece, Fletcher reveals that he knows Andrew testified against him and, as revenge, leads the band with a song Andrew does not know and has not been given the sheet music for. Andrew walks off stage humiliated, but then returns to the stage and cuts off Fletcher's introduction to their next piece by playing \"Caravan,\" cueing in the band himself. Fletcher is taken aback but resumes conducting. After Fletcher cues to the last beat of the piece, Andrew continues playing, performing an extended solo. After a moment of disbelief, Fletcher nods in approval of Andrew's performance before cueing the band finale. ")
            movie1.actors.addAll(listOf("Miles Teller", "J.K. Simmons"))
            movie1.genre = listOf("Drama", "Music")
            movie1.director.add("Damien Chazelle")
            movie1.rating = 5.0F
            movie1.imageId = R.drawable.posterwhiplash

            val movie2 = Movie("Cleopatra", "In 47 BC, Egypt is in civil war. Cleopatra VII, Egypt's rightful Queen, is in exile, while her sister Arsinoe and brother, Ptolemy have stolen the throne. Roman general Julius Caesar comes to Alexandria to collect Egypt's tax debt. Cleopatra smuggles herself into the palace wrapped in a carpet; a gift from her to Caesar. The two spend the night together, and the next morning, Cleopatra and Ptolemy are betrothed to marry by Caesar. Cleopatra is proclaimed Queen of Egypt. Caesar then orders the death of the unscrupulous Prime Minister Pothinus, prompting Ptolemy and Arsinoe to flee and return with their army to drive their sister out of Alexandria.\n" +
                    "\n" + "A battle breaks out between the Romans and the Egyptian forces, and in the process, Alexandria's great library is burned to the ground. Arsinoe and Ptolemy are pursued by Roman forces. Arsinoe is captured while Ptolemy is killed when his carriage overturns. Cleopatra has Arsinoe strangled in her cell. Cleopatra and Caesar take a 2-month journey down the Nile aboard one of the Queen's elegant ships. Caesar comes under fire from the Roman Senate and his critic Brutus due to a crisis in Pontus. Caesar promptly leaves for Rome. Unbeknownst to Caesar, Cleopatra is pregnant with his child. A son is born to the queen roughly nine months later; he is named Caesarion, in honor of his father.\n" +
                    "\n" + "Back in Rome, Caesar invites Cleopatra to stay at one of his villas, just outside Rome. With her, she brings the couple's infant son. In front of his people (including wife Calpurnia), Cleopatra declares that Caesar is her son's father, publicly forcing his hand, and demanding that her son be allowed to rule both Egypt and Rome invoking the consternation of Brutus and Cassius. Believing that he should hold the same status as his Egyptian lover, Caesar demands he be declared King of Rome. Although they are hesitant to do so, the senate eventually grants Caesar's request. Now having been declared king, Caesar prepares his a conquest of Parthia. Although he accepts Caesarion as his child, Caesar denies the queen's request, causing Cleopatra to leave him.\n" +
                    "\n" + "Just before her return to Egypt, Cleopatra soon learns that Caesar has been assassinated at the hands of Brutus, Cassius and other senators. The burdens of ruling fall on the shoulders of Caesar's Roman heir and nephew, Octavian and Mark Antony who declares revenge and begins a war against Brutus and Cassius. In the process, both Cassius and Brutus commit suicide. Though Octavian desecrates Brutus' corpse by severing and displaying his head, creating a rift between him and Mark Antony. ")
            movie2.actors.addAll(listOf("Leonor Varela", "Timothy Dalton", "Billy Zane"))
            movie2.genre = listOf("Drama", "Historical")
            movie2.director.add("Franc Roddam")
            movie2.rating = 4.0F
            movie2.imageId = R.drawable.postercleopatra

            val movie3 = Movie("Raiders of the Lost Ark", "In 1936, American archaeologist Indiana Jones recovers a golden idol from a booby-trapped Peruvian temple. Rival archaeologist René Belloq corners him and steals the idol; Jones escapes in a waiting seaplane. After returning to America, two Army Intelligence agents approach Jones. They reveal Nazi German forces are excavating Tanis, and one of their telegrams mentions Jones's old mentor Abner Ravenwood. Jones deduces that the Nazis seek the Ark of the Covenant, which Adolf Hitler believes will make their army invincible. The agents recruit Jones to recover the Ark first.\n" +
                    "\n" + "At a bar in Nepal, Jones reunites with Ravenwood's daughter Marion—with whom Jones once had an illicit relatonship—and learns Ravenwood is dead. The bar is set ablaze during a scuffle with Gestapo agent Arnold Toht, who arrives to take a medallion from Marion. Toht attempts to recover the medallion from the flames, but only burns its image into his hand. Jones and Marion take the medallion and escape together.\n" +
                    "\n" + "They travel to Cairo, where they meet Jones' friend Sallah. He reveals Belloq is assisting the Nazis, and they have fashioned an incomplete replica medallion from the burns on Toht's hand. Nazi soldiers and mercenaries attack Jones, and Marion is seemingly killed, leaving Jones despondent. An imam deciphers the medallion for Jones. One side bears a warning against disturbing the Ark, the other the correct measurements for the \"staff of Ra\", an item used to locate the Ark. Jones and Sallah realize the Nazis are digging in the wrong location and infiltrate the Nazi dig site. They use the medallion and the correct staff of Ra to locate the Well of Souls, the Ark's resting place. They recover the Ark—a golden, intricately decorated chest—but are discovered by Belloq and the Nazis, who seize the Ark and seal Jones and Marion—who has been held captive by Belloq—inside the well. The pair escape through an opening and flee with a truck carrying the Ark. Alongside Marion, Jones arranges to transport the Ark to London aboard a tramp steamer.\n" +
                    "\n" + "A Nazi U-boat intercepts the steamer and seizes the Ark and Marion; Jones covertly boards the U-boat. The vessel travels to an island in the Aegean Sea, where Belloq intends to test the power of the Ark before presenting it to Hitler. En route, Jones ambushes the Nazi group and threatens to destroy the Ark, but is forced to surrender after Belloq deduces he would never destroy something historically significant and also wants to know if the Ark's power is real. The Nazis take Jones and Marion to the test site and restrain them. Belloq ceremonially opens the Ark but finds only sand inside. At Jones' instruction, he and Marion close their eyes to avoid looking at the opened Ark, as it releases spirits, flames, and bolts of energy that kill Belloq, Toht, and the assembled Nazis before sealing itself shut. Jones and Marion open their eyes to find the area cleared of bodies and their bindings removed. Back in Washington, D.C., the United States government rewards Jones and Marcus Brody for securing the Ark. Despite Jones' insistence, the agents state only that the Ark has been moved to an undisclosed location for study by \"top men\". In a large warehouse, the Ark is crated up and stored among countless other crates. ")
            movie3.actors.addAll(listOf("Harrison Ford", "Karen Allen"))
            movie3.genre = listOf("Adventure", "Action")
            movie3.director.add("Steven Spielberg")
            movie3.rating = 4.5F
            movie3.imageId = R.drawable.posterraidersofthelostarc

            list.add(movie1)
            list.add(movie2)
            list.add(movie3)
            
            return list
        }
    }
}